# main.yml
name: CI

on:
  push:
    branches: [ main ]

# Add this
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Stop pm2 process || true
        run: pm2 stop fastify-rpi-ci-demo
      - name: Start the server
        run: pm2 start server.js --name fastify-rpi-ci-demo
      - name: Save pm2 process
        run: pm2 save