# main.yml
name: CI

on:
  push:
    branches: [ main ]

# Add this
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Start server
        run: pm2 -V
        run: pm2 delete all — ||
        run: pm2 start server.js — name fastify-rpi-ci-demo -i 2
