# main.yml
name: CI

on:
  push:
    branches: [ main ]

# Add this
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - run: pm2 -V
      - name: Start server
        run: pm2 start server.js --watch -i max
      - run: pm2 list
