# main.yml
name: CI

on:
  push:
    branches: [ main ]

# Add this
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Check pm2 version
        run: pm2 -V
      - name: Stop all pm2 processes
        run: pm2 delete all || true
      - name: Start server
        run: pm2 start server.js -i 2
