# main.yml
name: CI

on:
  push:
    branches: [ main ]

# Add this
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Copy files to dist folder
        run: cp -a . /opt/fastify-rpi-ci-demo
